const knowledge=[
 {keys:['ميسي','ليونيل','كرة القدم'],answer:'ليونيل ميسي لاعب كرة قدم أرجنتيني يُعد من أبرز لاعبي التاريخ. فاز بكأس العالم 2022 مع الأرجنتين، وحقق عدة كرات ذهبية، واشتهر بصناعة اللعب والمراوغة والتسجيل بالقدم اليسرى.'},
 {keys:['ذكاء اصطناعي','الذكاء الاصطناعي','ai'],answer:'الذكاء الاصطناعي هو مجموعة تقنيات تجعل الحاسوب ينفذ مهام تحتاج عادةً إلى قدر من الفهم أو التعلّم، مثل تحليل الصور، فهم اللغة، التنبؤ، والتوصية. هذا الإصدار من أُفُق لا يستخدم نموذجًا خارجيًا؛ بل يبحث في قاعدة معرفة محلية.'},
 {keys:['إنترنت','الإنترنت','شبكة'],answer:'الإنترنت شبكة عالمية من أجهزة متصلة. عندما تفتح موقعًا، يرسل جهازك طلبًا عبر مزود الخدمة إلى خادم الموقع، ثم يعود المحتوى على شكل حزم بيانات، ويعرضها المتصفح لك.'},
 {keys:['وقت','تنظيم الوقت','إنتاجية'],answer:'ابدأ بتحديد ثلاث أولويات فقط لليوم، وقسّم كل مهمة إلى خطوة صغيرة، واستخدم فترات تركيز من 25 دقيقة مع استراحة قصيرة. راجع ما أنجزته في نهاية اليوم وعدّل خطتك.'},
 {keys:['مريخ','المريخ','كوكب'],answer:'المريخ رابع كواكب المجموعة الشمسية، ويُعرف بالكوكب الأحمر بسبب أكاسيد الحديد على سطحه. لديه غلاف جوي رقيق، وفصول، وقمران صغيران هما فوبوس وديموس.'},
 {keys:['السعودية','عاصمة','الرياض'],answer:'عاصمة المملكة العربية السعودية هي الرياض، وهي أكبر مدن المملكة ومركزها الإداري والاقتصادي.'},
 {keys:['برمجة','تعلم البرمجة','كود'],answer:'للبدء في البرمجة اختر لغة واحدة، مثل JavaScript أو Python، وتعلّم الأساسيات عبر مشاريع صغيرة: آلة حاسبة، قائمة مهام، ثم تطبيق بسيط. الممارسة اليومية أهم من حفظ كل شيء.'},
 {keys:['مرحبا','السلام','أهلا','هلا'],answer:'أهلًا وسهلًا بك! أنا أُفُق، مساعد معرفي محلي. اسألني عن أحد المواضيع الموجودة في قاعدة المعرفة أو أضف معلوماتك الخاصة إلى هذا الملف.'},
 {keys:['حمار','الحمّار','الحيوان'],answer:'الحمار حيوان ثديي أليف من فصيلة الخيليات، ويُعرف بقدرته على التحمل وقوته في حمل الأوزان والعمل في المناطق الوعرة. صوته يُسمّى النهيق، ويتغذى غالبًا على الأعشاب والحبوب.'},
 {keys:['قطة','قط','كلب','حيوان أليف'],answer:'الحيوانات الأليفة هي حيوانات يربيها الإنسان في المنزل أو بالقرب منه، ومن أشهرها القطط والكلاب والطيور. تحتاج إلى طعام مناسب وماء ورعاية صحية.'},
 {keys:['شمس','الشمس'],answer:'الشمس نجم يقع في مركز المجموعة الشمسية، وتدور حوله الكواكب. تمنح الأرض الضوء والحرارة، وهي المصدر الأساسي للطاقة التي تدعم الحياة عليها.'},
 {keys:['ماء','المياه'],answer:'الماء مركب كيميائي يتكون من الهيدروجين والأكسجين، ورمزه H₂O. وهو ضروري لحياة الإنسان والحيوان والنبات.'},
 {keys:['ما اسمك','من أنت','اسمك'],answer:'اسمي أُفُق. أنا مساعد معرفي محلي أجيب من قاعدة المعرفة الموجودة داخل الموقع، ولا أرسل أسئلتك إلى خدمة ذكاء اصطناعي خارجية.'},
 {keys:['شكرا','شكرًا','ممتاز'],answer:'العفو! يسعدني مساعدتك. جرّب أن تسألني عن أي موضوع موجود في قاعدة المعرفة.'}
];
const chatArea=document.querySelector('#chatArea'), welcome=document.querySelector('#welcome'), prompt=document.querySelector('#prompt'), sendBtn=document.querySelector('#sendBtn'), voiceBtn=document.querySelector('#voiceBtn'), voiceStatus=document.querySelector('#voiceStatus');
function addMessage(text,type){if(welcome)welcome.remove();const row=document.createElement('div');row.className=`message ${type}`;row.innerHTML=`<div class="avatar">${type==='user'?'أ':'✦'}</div><div><div class="bubble"></div><span class="message-meta">${type==='user'?'أنت':'أُفُق · معرفة محلية'} ${type==='assistant'?'<button class="speak-btn" title="قراءة الرد">◖</button>':''}</span></div>`;row.querySelector('.bubble').textContent=text;if(type==='assistant')row.querySelector('.speak-btn').addEventListener('click',()=>{if('speechSynthesis' in window){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='ar-SA';speechSynthesis.speak(utterance)}});chatArea.appendChild(row);chatArea.scrollTop=chatArea.scrollHeight}
function normalizeArabic(value){return value.toLowerCase().replace(/[ًٌٍَُِّْـ]/g,'').replace(/[إأآا]/g,'ا').replace(/ة/g,'ه').replace(/[؟?!.,،؛:()\[\]{}]/g,' ').replace(/\s+/g,' ').trim()}
function answer(q){const normalized=normalizeArabic(q);let best=null,score=0;for(const item of knowledge){const hits=item.keys.reduce((n,k)=>{const key=normalizeArabic(k);return n+(normalized.includes(key)?Math.max(1,key.split(' ').length):0)},0);if(hits>score){score=hits;best=item}}if(best)return best.answer;return 'لم أجد إجابة موثوقة لهذا السؤال في قاعدة المعرفة المحلية الحالية. أضفت الآن دعمًا أفضل للأسئلة العربية الشائعة، ويمكن توسيع الملف knowledge داخل app.js بإضافة أي موضوع جديد ومفاتيح بحث وإجابة.'}
function send(text){const q=(text??prompt.value).trim();if(!q)return;addMessage(q,'user');prompt.value='';prompt.style.height='auto';const typing=document.createElement('div');typing.className='message assistant typing';typing.innerHTML='<div class="avatar">✦</div><div><div class="bubble">أفكر في قاعدة المعرفة المحلية...</div></div>';chatArea.appendChild(typing);chatArea.scrollTop=chatArea.scrollHeight;setTimeout(()=>{typing.remove();const reply=answer(q);addMessage(reply,'assistant');},350)}
sendBtn.addEventListener('click',()=>send());prompt.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});prompt.addEventListener('input',()=>{prompt.style.height='auto';prompt.style.height=Math.min(prompt.scrollHeight,130)+'px'});document.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.question)));document.querySelector('#newChat').addEventListener('click',()=>location.reload());document.querySelector('#clearChat').addEventListener('click',()=>{chatArea.innerHTML='';location.reload()});
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(SpeechRecognition){const rec=new SpeechRecognition();rec.lang='ar-SA';rec.interimResults=false;rec.onstart=()=>{voiceBtn.classList.add('listening');voiceStatus.textContent='استمع... تحدث الآن'};rec.onend=()=>{voiceBtn.classList.remove('listening');voiceStatus.textContent=''};rec.onerror=()=>{voiceBtn.classList.remove('listening');voiceStatus.textContent='تعذر الوصول للمايك'};rec.onresult=e=>{prompt.value=e.results[0][0].transcript;send()};voiceBtn.addEventListener('click',()=>rec.start())}else{voiceBtn.title='الإملاء الصوتي غير مدعوم في هذا المتصفح';voiceBtn.addEventListener('click',()=>{voiceStatus.textContent='جرّب Chrome أو Edge لتفعيل المايك'})}
